name: wine-competition
channels:
  - conda-forge
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=1.4
  - pip
  - torch
  - tqdm
  - transformers
  - accelerate
  - bert_sklearn
  - pip:
    - ramp-workflow
